const SearchList = [
  {
    id: "0",
    companyName: "Bus Company 1",
    busType: "AC",
    arrivalTime: "10:05",
    departureTime: "10:10",
    duration: "3h 45m",
    availableSeats: 15,
    prevFare: 350,
    currentFare: 450,
    rating: "4.2",
    reviewersCount: 50,
  },
  {
    id: "1",
    companyName: "Bus Company 2",
    busType: "Non-AC",
    arrivalTime: "10:10",
    departureTime: "10:15",
    duration: "2h 30m",
    availableSeats: 22,
    prevFare: 400,
    currentFare: 550,
    rating: "3.8",
    reviewersCount: 30,
  },
  {
    id: "2",
    companyName: "Bus Company 3",
    busType: "AC",
    arrivalTime: "10:15",
    departureTime: "10:20",
    duration: "4h 10m",
    availableSeats: 18,
    prevFare: 450,
    currentFare: 600,
    rating: "4.5",
    reviewersCount: 120,
  },
  {
    id: "3",
    companyName: "Bus Company 4",
    busType: "Non-AC",
    arrivalTime: "10:20",
    departureTime: "10:25",
    duration: "3h 15m",
    availableSeats: 30,
    prevFare: 350,
    currentFare: 400,
    rating: "3.7",
    reviewersCount: 25,
  },
  {
    id: "4",
    companyName: "Bus Company 5",
    busType: "AC",
    arrivalTime: "10:25",
    departureTime: "10:30",
    duration: "5h 0m",
    availableSeats: 12,
    prevFare: 600,
    currentFare: 650,
    rating: "4.0",
    reviewersCount: 80,
  },
  {
    id: "5",
    companyName: "Bus Company 6",
    busType: "Non-AC",
    arrivalTime: "10:30",
    departureTime: "10:35",
    duration: "4h 25m",
    availableSeats: 25,
    prevFare: 400,
    currentFare: 550,
    rating: "3.9",
    reviewersCount: 60,
  },
  {
    id: "6",
    companyName: "Bus Company 7",
    busType: "AC",
    arrivalTime: "10:35",
    departureTime: "10:40",
    duration: "3h 50m",
    availableSeats: 16,
    prevFare: 380,
    currentFare: 510,
    rating: "4.3",
    reviewersCount: 95,
  },
  {
    id: "7",
    companyName: "Bus Company 8",
    busType: "Non-AC",
    arrivalTime: "10:40",
    departureTime: "10:45",
    duration: "3h 0m",
    availableSeats: 28,
    prevFare: 350,
    currentFare: 400,
    rating: "3.6",
    reviewersCount: 40,
  },
  {
    id: "8",
    companyName: "Bus Company 9",
    busType: "AC",
    arrivalTime: "10:45",
    departureTime: "10:50",
    duration: "4h 15m",
    availableSeats: 20,
    prevFare: 450,
    currentFare: 500,
    rating: "4.4",
    reviewersCount: 110,
  },
  {
    id: "9",
    companyName: "Bus Company 10",
    busType: "Non-AC",
    arrivalTime: "10:50",
    departureTime: "10:55",
    duration: "3h 30m",
    availableSeats: 19,
    prevFare: 400,
    currentFare: 480,
    rating: "3.5",
    reviewersCount: 70,
  },
  {
    id: "10",
    companyName: "Bus Company 11",
    busType: "AC",
    arrivalTime: "10:55",
    departureTime: "11:00",
    duration: "3h 40m",
    availableSeats: 14,
    prevFare: 500,
    currentFare: 570,
    rating: "4.0",
    reviewersCount: 50,
  },
  {
    id: "11",
    companyName: "Bus Company 12",
    busType: "Non-AC",
    arrivalTime: "11:00",
    departureTime: "11:05",
    duration: "2h 50m",
    availableSeats: 26,
    prevFare: 370,
    currentFare: 420,
    rating: "3.8",
    reviewersCount: 65,
  },
  {
    id: "12",
    companyName: "Bus Company 13",
    busType: "AC",
    arrivalTime: "11:05",
    departureTime: "11:10",
    duration: "3h 30m",
    availableSeats: 18,
    prevFare: 430,
    currentFare: 500,
    rating: "4.1",
    reviewersCount: 90,
  },
  {
    id: "13",
    companyName: "Bus Company 14",
    busType: "Non-AC",
    arrivalTime: "11:10",
    departureTime: "11:15",
    duration: "4h 20m",
    availableSeats: 21,
    prevFare: 400,
    currentFare: 530,
    rating: "3.7",
    reviewersCount: 55,
  },
  {
    id: "14",
    companyName: "Bus Company 15",
    busType: "AC",
    arrivalTime: "11:15",
    departureTime: "11:20",
    duration: "3h 15m",
    availableSeats: 10,
    prevFare: 450,
    currentFare: 490,
    rating: "4.2",
    reviewersCount: 80,
  },
  {
    id: "15",
    companyName: "Bus Company 16",
    busType: "Non-AC",
    arrivalTime: "11:20",
    departureTime: "11:25",
    duration: "4h 5m",
    availableSeats: 30,
    prevFare: 390,
    currentFare: 460,
    rating: "3.9",
    reviewersCount: 40,
  },
  {
    id: "16",
    companyName: "Bus Company 17",
    busType: "AC",
    arrivalTime: "11:25",
    departureTime: "11:30",
    duration: "4h 10m",
    availableSeats: 12,
    prevFare: 480,
    currentFare: 550,
    rating: "4.3",
    reviewersCount: 100,
  },
  {
    id: "17",
    companyName: "Bus Company 18",
    busType: "Non-AC",
    arrivalTime: "11:30",
    departureTime: "11:35",
    duration: "3h 0m",
    availableSeats: 23,
    prevFare: 410,
    currentFare: 490,
    rating: "4.0",
    reviewersCount: 75,
  },
  {
    id: "18",
    companyName: "Bus Company 19",
    busType: "AC",
    arrivalTime: "11:35",
    departureTime: "11:40",
    duration: "3h 25m",
    availableSeats: 20,
    prevFare: 460,
    currentFare: 510,
    rating: "4.5",
    reviewersCount: 130,
  },
];

export default SearchList;
